apiVersion: apps/v1
kind: Deployment
metadata: { name: frontend }
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata:
      labels: { app: frontend }
      annotations:
        ad.datadoghq.com/nginx.logs: |
          [{"source":"nginx","service":"frontend"}]
    spec:
      containers:
      - name: frontend
        image: yourrepo/frontend-react:0.1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: { name: frontend-svc }
spec:
  selector: { app: frontend }
  ports: [{ port: 80, targetPort: 80 }]
