apiVersion: v1
kind: ConfigMap
metadata: { name: postgres-init-sql }
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id       VARCHAR(64) PRIMARY KEY,
      pw_hash  TEXT        NOT NULL
    );
    INSERT INTO users(id, pw_hash) VALUES ('demo', 'demo') ON CONFLICT DO NOTHING;
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: postgres }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - { name: POSTGRES_DB, value: "app" }
        - { name: POSTGRES_USER, value: "app" }
        - { name: POSTGRES_PASSWORD, value: "app" }
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: postgres-init-sql
---
apiVersion: v1
kind: Service
metadata: { name: postgres }
spec:
  selector: { app: postgres }
  ports: [{ port: 5432, targetPort: 5432 }]
